# see: https://github.com/marketplace/actions/test-compile-for-arduino

name: build
on: [push, pull_request]
jobs:
  build:
    name: build for MCU
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Compile sketch
      uses: ArminJo/arduino-test-compile@v3
      with:
        #arduino-board-fqbn: esp32:esp32:m5stack-atoms3:CDCOnBoot=cdc
        #arduino-platform: esp32:esp32@2.3.1
        #platform-url: https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json
        arduino-board-fqbn: esp32:esp32:m5stack-atoms3:CDCOnBoot=cdc
        arduino-platform: esp32:esp32@2.0.17
        #arduino-platform: esp32:esp32@3.1.0
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: M5AtomS3@1.0.0,M5Unified@0.2.3
        sketch-names: "*/*.ino"
        sketch-names-find-start: bbn_*
        extra-arduino-cli-args: "--warnings default "
        set-build-path: true
        
